# Generated by Django 5.2.8 on 2025-11-08 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("taxi", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="car",
            options={"ordering": ["model", "manufacturer"]},
        ),
    ]
